In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
b=np.array([[1,2],[3,4]])

In [5]:
print("1D array:",a)
print("2D array:\n",b)

1D array: [1 2 3]
2D array:
 [[1 2]
 [3 4]]


In [6]:
print("shape:",b.shape)
print("datatype:",b.dtype)
print("size:",b.size)

shape: (2, 2)
datatype: int32
size: 4


In [7]:
x=np.array([10,20,30])

In [8]:
y=np.array([1,2,3])

In [9]:
print("addition:",x+y)
print("multiplication:",x*y)
print("square root:",np.sqrt(x))

addition: [11 22 33]
multiplication: [10 40 90]
square root: [3.16227766 4.47213595 5.47722558]


In [13]:
arr=np.arange(0,10,2)

In [14]:
reshaped=arr.reshape(1,5)

In [15]:
print("arange:",arr)
print("reshaped:",reshaped)

arange: [0 2 4 6 8]
reshaped: [[0 2 4 6 8]]


In [16]:
data=np.array([10,15,20,25,30])

In [17]:
print("greater than 20:",data[data>20])

greater than 20: [25 30]


In [18]:
np.random.seed(0)

In [20]:
print("random integer:",np.random.randint(1,100,size=(2,3)))

random integer: [[45 48 65]
 [68 68 10]]


In [23]:
a=np.zeros((2,3))

In [24]:
b=np.ones((3,3))

In [25]:
c=np.eye(4)

In [26]:
print("zeros:\n",a)
print("ones:\n",b)
print("identity matrix:\n",c)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [27]:
arr=np.arange(12)

In [28]:
reshaped=arr.reshape(3,4)

In [29]:
flattened=reshaped.flatten()

In [30]:
print("reshaped array:\n",reshaped)
print("flattened array:",flattened)

reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [32]:
A=np.array([[1,2],[3,4]])

In [33]:
B=np.array([[5,6],[7,8]])

In [34]:
result=np.dot(A,B)

In [35]:
print("matrix A:\n",A)
print("matrix B:\n",B)
print("dot product of AxB:\n",result)

matrix A:
 [[1 2]
 [3 4]]
matrix B:
 [[5 6]
 [7 8]]
dot product of AxB:
 [[19 22]
 [43 50]]


In [36]:
a=np.array([[1],[2],[3]])

In [37]:
b=np.array([10,20,30])

In [38]:
result=a+b

In [39]:
print("broadcasted addition:\n",result)

broadcasted addition:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [40]:
data=np.array([10,20,30,40,50])

In [41]:
print("mean:\n",np.mean(data))
print("median:\n",np.median(data))
print("standard devation:\n",np.std(data))
print("variance:\n",np.var(data))

mean:
 30.0
median:
 30.0
standard devation:
 14.142135623730951
variance:
 200.0


In [42]:
arr=np.array([5,15,25,35,45])

In [43]:
filtered=np.where(arr>20,"high","low")

In [44]:
print("original array:\n",arr)
print("labels:\n",filtered)

original array:
 [ 5 15 25 35 45]
labels:
 ['low' 'low' 'high' 'high' 'high']


In [45]:
arr=np.array([50,10,20,40,30])

In [46]:
sort_arr=np.sort(arr)

In [47]:
index=np.where(arr==40)

In [49]:
print("Sorted:",sort_arr)
print("Index of 40:",index[0])

Sorted: [10 20 30 40 50]
Index of 40: [3]


In [50]:
np.random.seed(0)

In [51]:
rand_arr=np.random.rand(3,3)

In [52]:
normal_arr=np.random.rand(3,3)

In [53]:
print("random uniform array:\n",rand_arr)
print("random uniform array:\n",normal_arr)

random uniform array:
 [[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]
random uniform array:
 [[0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985]]


In [54]:
a=np.array([1,2,3,4])

In [55]:
b=np.array([3,4,5,6])

In [59]:
print("union:",np.union1d(a,b))
print("intersection:",np.intersect1d(a,b))
print("set difference:",np.setdiff1d(a,b))

union: [1 2 3 4 5 6]
intersection: [3 4]
set difference: [1 2]
